[package]
name = "rustle"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies.cp437_constants]
version = "1.0.2"

[[example]]
name = "demo"